---
title: get to class
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
name: Get To Class
author:
  name: Emil Sayahi
  "//facebook": your-id
  twitter: gettoclassblah
  github: FHEDUEmil
  "//linkedin": your-id
  "//medium": your-id
  "//tumblr": your-id
  email: postmaster@mail.gettoclass.cf
google-analytics:
  id: UA-85744932-1
disqus:
  id: gettoclass
url: https://fheduemil.github.io/
baseurl: 
permalink: "/:year-:month-:day/:title/"
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  imput: GFM
nav:
- name: About
  url: "/about"
- name: Archive
  url: "/archive"
- name: Tags
  url: "/tags"
- name: GitHub
  url: https://github.com/FHEDUEmil
sass:
  sass_dir: _sass
  style: compressed
gems:
- jekyll-seo-tag
- jekyll-paginate
exclude:
- vendor
